### ISSUE TITLE
5.3 Create a Slideshow.

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/jquery#8]
https://github.com/osifoanosike/jquery/tree/master/exercise5_3

5.3 Create a Slideshow.
This is a tough one if you do not know JS basics and particularly scopes.Open the file /exercises/index.html in your browser. Use the file /exercises/js/slideshow.js. Your task is to take a plain semantic HTML page and enhance it with JavaScript by adding a slideshow.
Move the #slideshow element to the top of the body.
Write code to cycle through the list items inside the element; fade one in, display it for a few seconds, then fade it out and fade in the next one.
When you get to the end of the list, start again at the beginning.
For an extra challenge, create a navigation area under the slideshow that shows how many images there are and which image you're currently viewing. (Hint: $.fn.prevAll will come in handy for this.)

**Comment by Shruti2791** [comment]
1) Shouldn't be #start_slideshow be called from #init only ?
2) No need for passing 'total_slide_count' to #update_nav_area as it is already a class attribute.
3) Can't the images be made the attribute of the class as well ? This would reduce the DOM hits to fetch first image in your case.

**Comment by osifoanosike** [comment]
Fixed. Thanks

**Comment by Shruti2791** [comment]
1) Please follow proper directory structure. Keep all the js library files into libs folder.
2) Why do we need to hit the DOM everywhere for '#slideshow' when we have variable slides being passed to SlideShow class ?
3) There is still a better way instead of making these (eg: Line no. 9, 16 34 ) complex DOM hits.

**Comment by osifoanosike** [comment]
Corrected

**Comment by Shruti2791** [comment]
1) Instead of using the complex selector in line no 9 , can't we simply hide all and just show the first ?
2) Can't we simply calculate the number to be shown inside #update_nav_area itself ? So that we do not have to pass number by adding 1 to it from everywhere (Discuss if not clear).
3) We can simplify what is being done in line 16.
4) Can we make first child of the slides an attribute for the class as its being used at various places ?
5) libs should be a sibling folder to js.
6) Method names and variable names should be in lower camel case.

**Comment by osifoanosike** [comment]
Code corrected

**Comment by Shruti2791** [comment]
Looks good :+1:
